[package]
name = "payments-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
rust_decimal = "1"

[dev-dependencies]
gag = "1.0"
rust_decimal_macros = "1"
serial_test = "0.7"
